// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"


import ReadMore from 'stimulus-read-more'
import HelloController from "./hello_controller"
application.register("hello", HelloController)
application.register('read-more', ReadMore)
import Reveal from 'stimulus-reveal-controller'
application.register("reveal", Reveal)
