// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
import ReadMore from 'stimulus-read-more'
import HelloController from "./hello_controller"

import SearchAnimesController from "./search_animes_controller"

application.register("hello", HelloController)

application.register("search-animes", SearchAnimesController)

application.register('read-more', ReadMore)
import Reveal from 'stimulus-reveal-controller'
application.register("reveal", Reveal)
import CharacterCounter from 'stimulus-character-counter'
application.register("character-counter", CharacterCounter)
import TextareaAutogrow from 'stimulus-textarea-autogrow'
application.register("textarea-autogrow", TextareaAutogrow)
