meta_name: "AnimeTrek"
meta_title: "AnimeTrek - Discover, Explore, Simplify"
meta_description: "AnimeTrek is a platform to discover and explore anime. It is a place to find information about your favorite anime."
meta_image: "https://res.cloudinary.com/dtjuz4kkr/image/upload/v1686851125/animetrek_logo_fnexfu.png"
meta_url: "https://animetrek.me/"
meta_keywords: "Anime, AnimeTrek, Animes"
